easy_admin:
    entities:
      Category:
        class:  App\Entity\Category
      Wallpaper:
              class:  App\Entity\Wallpaper
              list:
                fields:
                  - "id"
                  - "filename"
                  - "slug"
                  - {property: "width", format: "%d"}
                  - {property: "height", format: "%d"}
                  - {property: "image", type: "image", base_path: "/images/"}
              form:
                fields:
                  - {property: "file", type: "file"}
                  - "slug"
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
